# Generated by Django 4.2.7 on 2023-11-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                ("nomeProjeto", models.CharField(max_length=100)),
                ("responsavel", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=1000)),
                ("contatoTelefone", models.CharField(max_length=14)),
                ("contatoEmail", models.EmailField(max_length=254)),
                ("contatoRedeSociais", models.CharField(max_length=50)),
                ("demanda", models.TextField(max_length=1000)),
                (
                    "idProjeto",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
