# Generated by Django 4.2.7 on 2023-11-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Projeto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demanda",
            fields=[
                (
                    "idDemanda",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nomeDemanda", models.CharField(max_length=50)),
                ("descricaoDemanda", models.TextField(max_length=200)),
                ("contatoDemanda", models.CharField(max_length=50)),
                (
                    "idProjetoDemanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="demandas",
                        to="Projeto.projeto",
                    ),
                ),
            ],
        ),
    ]
