# Generated by Django 4.2.7 on 2023-11-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doacao",
            fields=[
                ("valorDoado", models.FloatField()),
                ("momentoDoacao", models.DateTimeField()),
                (
                    "idDoacao",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "nomeDoador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
